kind: Deployment
apiVersion: apps/v1
metadata:
  name: desktop
  namespace: default
spec:
  selector:
    matchLabels:
      app: desktop
  template:
    metadata:
      labels:
        app: desktop
    spec:
      restartPolicy: Always
      containers:
        - name: ubuntu-xfce
          image: deserializeme/ubuntu-xfce
          env:
          - name: "RESOLUTION"
            value: "1920x1080"
          command:
            - /bin/sleep
            - 3650d
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              name: "http"
            - containerPort: 443
              name: "https"
            - containerPort: 22
              name: "ssh"
            - containerPort: 3389
              name: "rdp"
            - containerPort: 5900
              name: "vnc"
            - containerPort: 8080
              name: "novnc"
          volumeMounts:
          - mountPath: /tmp
            name: backups
      volumes:
      - name: backups
        persistentVolumeClaim:
          claimName: swfs-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: desktop
spec:
  selector:
    app: desktop
  ports:
    - name: ssh
      port: 22
      targetPort: 22
      protocol: TCP
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
    - name: rdp
      port: 3389
      targetPort: 3389
      protocol: TCP
    - name: vnc
      port: 5900
      targetPort: 5900
      protocol: TCP
    - name: novnc
      port: 8080
      targetPort: 8080
      protocol: TCP
  type: LoadBalancer


