kind: Deployment
apiVersion: apps/v1
metadata:
  name: desktop
  namespace: default
spec:
  selector:
    matchLabels:
      app: desktop
  template:
    metadata:
      labels:
        app: desktop
    spec:
      restartPolicy: Always
      containers:
        - name: ubuntu-xfce
          image: deserializeme/debian-xfce
          env:
          - name: "RESOLUTION"
            value: "1920x1080"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3389
              name: "rdp"
            - containerPort: 5900
              name: "vnc"
            - containerPort: 8080
              name: "novnc"
          volumeMounts:
          - mountPath: /home/player1/shared
            name: shared
      volumes:
      - name: shared
        persistentVolumeClaim:
          claimName: swfs-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: desktop
spec:
  selector:
    app: desktop
  ports:
    - name: rdp
      port: 3389
      targetPort: 3389
      protocol: TCP
    - name: vnc
      port: 5900
      targetPort: 5900
      protocol: TCP
    - name: novnc
      port: 8080
      targetPort: 8080
      protocol: TCP
  type: LoadBalancer


